<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);packages\**</DefaultItemExcludes>
    <RootNamespace>SuperDentist.App</RootNamespace>
    <AssemblyName>Super Dentist</AssemblyName>
    <StartupObject>SuperDentist.App.App</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\SuperDentist.Core\SuperDentist.Core.csproj" />
    <ProjectReference Include="$(MSBuildThisFileDirectory)..\SuperDentist.Infrastructure\SuperDentist.Infrastructure.csproj" />
    <ProjectReference Include="..\SuperDentist.Application\SuperDentist.Application.csproj" />
  </ItemGroup>



  <ItemGroup>
    <Resource Include="Assets\**\*.*" />
    <Resource Include="Icons\**\*.*" />
    <Resource Include="DentalTool2.jpg" />
    <Resource Include="close-window.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
